api:
  build: api
  links:
    - mysql:mysql.cloud66.local
  ports:
  - "3000:80"
  volumes:
    - ${PWD}/api:/home/app

test:
  build: test
  links:
    - mysql:mysql.cloud66.local
    - api
  volumes:
    - ${PWD}/test:/app

mysql:
  image: mysql
  ports:
  - "3306:3306"
  environment:
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test 