api:
  build: api
  links:
    - mysql:mysql.cloud66.local
  ports:
  - "3000:80"
  volumes:
    - ${PWD}/api:/app
  environment:
    - MYSQL_ADDRESS=mysql.cloud66.local
    - MYSQL_DATABASE=development
    - MYSQL_USERNAME=test
    - MYSQL_PASSWORD=test  

test:
  build: api
  command: mocha
  links:
    - mysql:mysql.cloud66.local
  volumes:
    - ${PWD}/api:/app
  environment:
    - MYSQL_ADDRESS=mysql.cloud66.local
    - MYSQL_DATABASE=test
    - MYSQL_USERNAME=test
    - MYSQL_PASSWORD=test 

mysql:
  image: mysql
  ports:
  - "3306:3306"
  environment:
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test 