server:
  build: server
  links:
    - mongo:mongodb.cloud66.local
  ports:
  - "3000:80"
  volumes:
    - ${PWD}/api:/app

test:
  build: test
  links:
    - mongo:mongodb.cloud66.local
    - api
  volumes:
    - ${PWD}/api:/app

mongo:
  image: mongo