# the infamous api
api:
  build: services/api
  ports:
  - "3000:80"
  links:
    - mysql
    - mysql:mysql.cloud66.local
  environment:
    - MYSQL_ADDRESS=mysql.cloud66.local
    - MYSQL_DATABASE=test
    - MYSQL_USERNAME=test
    - MYSQL_PASSWORD=test  

# test suite to test the api outside-in
test:
  build: services/test
  links:
    - api
    - mysql
    - api:api.cloud66.local
    - mysql:mysql.cloud66.local
  environment:
    - API_ADDRESS=api.cloud66.local

# a mysql db for data storage
mysql:
  image: mysql
  environment:
    - MYSQL_DATABASE=test
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test  

# a notifier script to tell cloud66 to redeploy our well tested api service
notifier:
  build: services/notifier
  command: echo "don't use the cloud66 redeployhook notifier on your local machine"
