api:
  build: api
  links:
    - mysql:mysql.cloud66.local
  ports:
  - "3000:80"
  volumes:
    - ${PWD}/api:/home/app

test:
  build: test
  links:
    - mysql:mysql.cloud66.local
    - api
  volumes:
    - ${PWD}/test:/app

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true 